import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export async function generateMetadata({ params }: { [key: string]: any }) {
  return {
    title: 'Home',
    description: 'Generated by create next app',
  }
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black text-white`}>
        <header className="bg-gray-400 w-full">
          <nav>
            <ul className="flex justify-between px-5 py-1">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="about">About</Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
