import { Inter } from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'
import { Providers } from '@/app/[locale]/providers'
import CustomNavbar from '@/app/[locale]/_components/Navbar'
import { i18n, Locale } from '@/i18n-config'
import { getDictionary } from '@/get-dictionary'

const inter = Inter({ subsets: ['latin'] })

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ locale }))
}

export async function generateMetadata({ params }: { [key: string]: any }) {
  return {
    title: 'Home',
    description: 'Generated by create next app',
  }
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: ReactNode
  params: { locale: Locale }
}) {
  const dictionary = await getDictionary(locale)

  const navDic = dictionary.navbar

  return (
    <html lang={locale} className="dark">
      <body className={`${inter.className}`}>
        <Providers>
          <CustomNavbar params={{ dictionary: navDic, locale }} />
          {children}
        </Providers>
      </body>
    </html>
  )
}
